-- 废弃：此 SQL 文件不再被 association_service.py 加载使用
-- 实例关联表已按模型分表，表名格式：cc_InstAsst_0_pub_{obj_id}
-- 实际插入逻辑见 app/service/association_service.py 中的 create_instance_association
-- 创建关联时需双向插入到源模型和目标模型的分表（与原项目一致）
-- 该文件保留仅作历史参考，请勿通过文件路径加载
--
-- 历史插入（单表，已废弃）：
-- INSERT INTO cc_InstAsst_0_pub
-- (_id, id, bk_obj_id, bk_inst_id, bk_asst_obj_id, bk_asst_inst_id, bk_obj_asst_id, bk_relation_type_id, bk_supplier_account)
-- VALUES (:_id, :id, :bk_obj_id, :bk_inst_id, :bk_asst_obj_id, :bk_asst_inst_id, :bk_obj_asst_id, :bk_relation_type_id, :bk_supplier_account)
--
-- 当前插入（分表，需动态拼接表名，双向插入）：
-- 1. 源模型分表: INSERT INTO "cc_InstAsst_0_pub_{bk_obj_id}" ...
-- 2. 目标模型分表: INSERT INTO "cc_InstAsst_0_pub_{bk_asst_obj_id}" ...（当源≠目标时）
