-- 废弃：此 SQL 文件不再被 association_service.py 加载使用
-- 实例关联表已按模型分表，表名格式：cc_InstAsst_0_pub_{obj_id}
-- 实际查询逻辑见 app/service/association_service.py 中的 get_instance_associations / find_instance_associations
-- 该文件保留仅作历史参考，请勿通过文件路径加载
--
-- 历史查询（单表，已废弃）：
-- SELECT * FROM cc_InstAsst_0_pub
--
-- 当前查询（分表，需动态拼接表名）：
-- SELECT * FROM "cc_InstAsst_0_pub_{obj_id}"
-- WHERE bk_inst_id = :instance_id OR bk_asst_inst_id = :instance_id
